version: '3'
services:
  prometheus:
    container_name: prometheus0
    ports:
      - "9090:9090"
    image: "${IMAGE}"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
      - "--web.enable-admin-api"
    volumes:
      - ${DATAVOLUME}:/prometheus
      - ${CONFIGFILE}:/etc/prometheus/prometheus.yml
    restart:
      always
